### ISSUE TITLE
Industrialized Heat v1 (is this the right place to send sumbitions?)

### ISSUE THREAD

**Issue by Rob07erto** [Ethan76167/TRIA.OS-Difficulty-List#21]
Industrialized Heat v1
Map ID: 10128277453
Map Creator: MalachiLeapYear, aj_irlu, Dogeflied, 06xser, RaxdiiGames, RFAStudio & mawi
Map Music: https://www.youtube.com/watch?v=NJdYxqOOjjI&t=0s
https://www.youtube.com/watch?v=6pw7iw99U7U&ab_channel=gabriel1373yt

**Comment by RockyTanker** [comment]
Hi!

Unfortunately this is not the correct place for making entries. Refer to:
https://discord.gg/EuaQNXnqDR
